name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  XPMKitTests:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: swift test --filter XPMKitTests
  
  XPMTests:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: swift test --filter XPMTests
